// Generated by scripts/generate-locales.ts; run `yarn locales:generate` rather than editing.
import en from "./en.json" with { type: "json" };
import de from "./de.json" with { type: "json" };
import es from "./es.json" with { type: "json" };
import fr from "./fr.json" with { type: "json" };
import nl from "./nl.json" with { type: "json" };
import pt from "./pt.json" with { type: "json" };
import ptBR from "./pt-BR.json" with { type: "json" };

/** Every message key, with the English wording as the type's source of truth. */
export type Messages = typeof en;

export const messages = { en, de, es, fr, nl, pt, "pt-BR": ptBR } satisfies Record<string, Partial<Messages>>;
