// Generated by scripts/generate-locales.ts; run `yarn locales:generate` rather than editing.
import en from "./en.json" with { type: "json" };

/** Every message key, with the English wording as the type's source of truth. */
export type Messages = typeof en;

export const messages = { en } satisfies Record<string, Partial<Messages>>;
